/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface QsStockPicker {
        "heading": string;
    }
    interface QsTooltipDisplay {
        "text": string;
    }
}
declare global {
    interface HTMLQsSideDrawerElement extends Components.QsSideDrawer, HTMLStencilElement {
    }
    var HTMLQsSideDrawerElement: {
        prototype: HTMLQsSideDrawerElement;
        new (): HTMLQsSideDrawerElement;
    };
    interface HTMLQsStockPickerElement extends Components.QsStockPicker, HTMLStencilElement {
    }
    var HTMLQsStockPickerElement: {
        prototype: HTMLQsStockPickerElement;
        new (): HTMLQsStockPickerElement;
    };
    interface HTMLQsTooltipDisplayElement extends Components.QsTooltipDisplay, HTMLStencilElement {
    }
    var HTMLQsTooltipDisplayElement: {
        prototype: HTMLQsTooltipDisplayElement;
        new (): HTMLQsTooltipDisplayElement;
    };
    interface HTMLElementTagNameMap {
        "qs-side-drawer": HTMLQsSideDrawerElement;
        "qs-stock-picker": HTMLQsStockPickerElement;
        "qs-tooltip-display": HTMLQsTooltipDisplayElement;
    }
}
declare namespace LocalJSX {
    interface QsSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface QsStockPicker {
        "heading"?: string;
    }
    interface QsTooltipDisplay {
        "text"?: string;
    }
    interface IntrinsicElements {
        "qs-side-drawer": QsSideDrawer;
        "qs-stock-picker": QsStockPicker;
        "qs-tooltip-display": QsTooltipDisplay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qs-side-drawer": LocalJSX.QsSideDrawer & JSXBase.HTMLAttributes<HTMLQsSideDrawerElement>;
            "qs-stock-picker": LocalJSX.QsStockPicker & JSXBase.HTMLAttributes<HTMLQsStockPickerElement>;
            "qs-tooltip-display": LocalJSX.QsTooltipDisplay & JSXBase.HTMLAttributes<HTMLQsTooltipDisplayElement>;
        }
    }
}
